// Generated by CoffeeScript 1.6.2
(function() {
  var Ball, Bar;

  Ball = (function() {
    function Ball(properties) {
      this.pos = properties.pos, this.vel = properties.vel, this.src = properties.src, this.dest = properties.dest;
    }

    Ball.update = function(bar) {
      var angle, height, newx, newy, paused, width;

      width = game.options.w;
      height = game.options.h;
      newx = this.ball.vel.x + this.ball.pos.x;
      newy = this.ball.vel.y + this.ball.pos.y;
      if (newy - this.ball.size < 0) {
        this.ball.vel.y *= -1;
      } else if (newx - this.ball.size < 0 || newx + this.ball.size > width) {
        this.ball.vel.x *= -1;
      } else if (newy + this.ball.size / 2 > bar.y && Math.abs(newx - bar.x) < bar.width / 2) {
        this.ball.vel.y *= -1;
        angle = 3 * Math.sin(Math.abs(bar.x - this.ball.pos.x) / (bar.width / 2));
        this.ball.vel.x *= angle;
      } else if (newy >= height) {
        this.ball.pos.x = Math.floor(Math.random() * width);
        this.ball.pos.y = Math.floor(Math.random() * height);
        paused = true;
      }
      this.ball.pos.x += this.ball.vel.x;
      return this.ball.pos.y += this.ball.vel.y;
    };

    return Ball;

  })();

  Bar = (function() {
    function Bar(properties) {}

    Bar.prototype.move = delta(function() {
      this.pos.x += delta.x;
      this.pos.y += delta.y;
      return this.pos;
    });

    return Bar;

  })();

}).call(this);
